#!/usr/bin/env python3
"""Bring the three hand-written membrane pages onto the site shell.

These were generated by older scripts with their own dark palette and their own
nav. Rather than regenerate them (the inspector is a working three.js app), the
site header is injected and their local palette is re-pointed at the site
tokens, so they inherit light/dark and the shared navigation.

Idempotent: re-running detects the marker and does nothing.

    python scripts/retheme_legacy.py
"""
from __future__ import annotations

import re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import site_shell as sh

ROOT = Path(__file__).resolve().parent.parent
MEM = ROOT / "docs" / "membranes"
MARK = "<!--rethemed-->"

# the app pages keep a dark interior (a 3D canvas wants one) but take their
# colours from the site tokens so the two never drift apart
APP_TOKENS = """<link rel="stylesheet" href="../assets/app.css">
<script src="../assets/site.js"></script>
<style>
 /* the viewer's own variables alias the site tokens, so it follows the theme;
    only the 3D viewport stays dark in both modes, because a lit surface reads
    better against it */
 :root{--bg:var(--bg);--card:var(--raise);--card2:var(--sunk);
       --ink:var(--ink);--muted:var(--ink-3);--line:var(--rule);--head:var(--ink)}
 body{font:var(--t3)/1.6 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
      background:var(--bg);color:var(--ink)}
 #side{background:var(--bg);border-right:1px solid var(--rule);padding:var(--s4)}
 #side h1{color:var(--ink);font-size:var(--t2);font-weight:600}
 #side p{color:var(--ink-3);font-size:var(--t4)}
 .grp{color:var(--ink-3);font-size:var(--t5);text-transform:uppercase;letter-spacing:.07em}
 .crop{background:none;border:0;border-bottom:1px solid var(--rule);border-radius:0;
       color:var(--ink);font-size:var(--t4);padding:6px 4px;margin:0}
 .crop:hover{background:var(--sunk)}
 .crop.active{background:var(--accent);color:#fff;border-radius:5px;border-bottom-color:transparent}
 .crop.active .chem,.crop.active .hpf{color:#fff}
 .chem{color:var(--chem)} .hpf{color:var(--hpf)}
 #main{background:#0d1016}
 #ctrl,#title{background:var(--raise);border:1px solid var(--rule);color:var(--ink);
              border-radius:var(--radius);box-shadow:0 8px 26px rgba(0,0,0,.18)}
 #ctrl select,.row input[type=number]{background:var(--bg);color:var(--ink);
   border:1px solid var(--rule-strong)}
 #ctrl label,#barlab,#nanleg,#hint{color:var(--ink-3);font-size:var(--t5)}
</style>"""

DOC_STYLE = """<style>
 body{background:var(--bg);color:var(--ink)}
 .container{max-width:var(--maxw);margin:0 auto;padding:var(--s6) var(--s4) var(--s7)}
 nav.bar{display:none}
 h1{font-size:var(--t1);margin:0 0 var(--s3);letter-spacing:-.02em;font-weight:600}
 h2{font-size:var(--t2);color:var(--ink);border-bottom:1px solid var(--rule);
    padding-bottom:var(--s2);margin:var(--s6) 0 var(--s3);font-weight:600}
 h3{color:var(--ink);margin:var(--s4) 0 var(--s2);font-size:var(--t3);font-weight:600}
 p,li{color:var(--ink-2)}
 table{border-collapse:collapse;width:100%;font-size:var(--t4);display:block;overflow-x:auto}
 th,td{border-bottom:1px solid var(--rule);padding:8px 14px 8px 0;text-align:left}
 th{color:var(--ink-3);font-size:var(--t5);text-transform:uppercase;letter-spacing:.07em;font-weight:500}
 code,pre{background:var(--sunk);border-radius:5px;padding:1px 5px;font-size:var(--t4)}
 pre{padding:var(--s3);overflow-x:auto}
 img{max-width:100%;border-radius:var(--radius)}
 .grid,.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:var(--s4)}
 .card,.item{background:var(--raise);border:1px solid var(--rule);border-radius:var(--radius);padding:var(--s3)}
</style>"""


def strip_local_palette(html: str) -> str:
    """Neutralise the old :root block so the site tokens win."""
    return re.sub(r":root\{--bg:#0f1420;[^}]*\}", "", html, count=1)


def inject(path: Path, active: str, doc_page: bool) -> bool:
    html = path.read_text()
    if MARK in html:
        print(f"  already themed: {path.name}")
        return False
    header = sh.nav(active, 1)
    css = DOC_STYLE if doc_page else ""
    base = ('<link rel="stylesheet" href="../assets/app.css">'
            '<script src="../assets/site.js"></script>')
    inject_head = ('<meta name="viewport" content="width=device-width,initial-scale=1">'
                   + (base + css if doc_page else APP_TOKENS) + MARK)

    if doc_page:
        html = strip_local_palette(html)

    # head injection: after </title> if present, else at the very top
    if "</title>" in html:
        html = html.replace("</title>", "</title>" + inject_head, 1)
    else:
        html = inject_head + html

    # body injection: right after <body...> if present, else before the first
    # structural element the page uses
    m = re.search(r"<body[^>]*>", html)
    if m:
        html = html[:m.end()] + header + html[m.end():]
    else:
        for anchor in ('<div id=app>', '<nav class=bar>', '<nav class="bar">',
                       '<div class=container>', '<div class="container">', '<h1'):
            if anchor in html:
                html = html.replace(anchor, header + anchor, 1)
                break
        else:
            html = header + html
    path.write_text(html)
    print(f"  themed: {path.name}")
    return True


def fix_inspector_height():
    """The app assumed the full viewport; it now sits under a 52px header."""
    p = MEM / "inspector.html"
    h = p.read_text()
    if "calc(100vh - 52px)" in h:
        return
    h = h.replace("#app{display:flex;height:100vh}",
                  "#app{display:flex;height:calc(100vh - 52px)}")
    p.write_text(h)
    print("  inspector: canvas height adjusted for the header")


def main():
    inject(MEM / "inspector.html", "membranes/inspector.html", doc_page=False)
    fix_inspector_height()
    inject(MEM / "methods.html", "membranes/inspector.html", doc_page=True)
    inject(MEM / "index.html", "membranes/views.html", doc_page=True)


if __name__ == "__main__":
    main()
