#!/usr/bin/env python3
"""Bring the three hand-written membrane pages onto the site shell.

These were generated by older scripts with their own dark palette and their own
nav. Rather than regenerate them (the inspector is a working three.js app), the
site header is injected and their local palette is re-pointed at the site
tokens, so they inherit light/dark and the shared navigation.

Idempotent: re-running detects the marker and does nothing.

    python scripts/retheme_legacy.py
"""
from __future__ import annotations

import re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import site_shell as sh

ROOT = Path(__file__).resolve().parent.parent
MEM = ROOT / "docs" / "membranes"
MARK = "<!--rethemed-->"

# the app pages keep a dark interior (a 3D canvas wants one) but take their
# colours from the site tokens so the two never drift apart
APP_TOKENS = """<link rel="stylesheet" href="../assets/app.css">
<script src="../assets/site.js"></script>
<style>
 /* the app's own variables now alias the site tokens, so it follows light/dark
    with everything else; only the 3D viewport stays dark in both modes, because
    a lit surface reads better against it */
 :root{--bg:var(--surface-0);--card:var(--surface-1);--card2:var(--surface-2);
       --ink:var(--text-primary);--muted:var(--text-muted);--head:var(--text-primary)}
 body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
      background:var(--surface-0);color:var(--text-primary)}
 #side{background:var(--surface-1);border-right:1px solid var(--line)}
 #side h1{color:var(--text-primary)} #side p{color:var(--text-muted)}
 .grp{color:var(--text-muted)}
 .crop{background:var(--surface-2);border:1px solid var(--line);color:var(--text-primary)}
 .crop:hover{background:var(--surface-3)}
 .crop.active{background:var(--accent);border-color:var(--accent);color:#fff}
 .crop.active .chem,.crop.active .hpf{color:#fff}
 #main{background:radial-gradient(circle at 50% 40%,#1e2430,#0d1016)}
 #ctrl,#title{background:var(--surface-1);border:1px solid var(--line);color:var(--text-primary)}
 #ctrl select,.row input[type=number]{background:var(--surface-2);color:var(--text-primary);
   border:1px solid var(--line)}
 #ctrl label,#barlab,#nanleg,#hint{color:var(--text-muted)}
</style>"""

DOC_STYLE = """<style>
 body{background:var(--surface-0);color:var(--text-primary)}
 .container{max-width:var(--maxw);margin:0 auto;padding:28px 20px 80px}
 nav.bar{display:none}
 h1{font-size:25px;margin:0 0 8px;letter-spacing:-.022em}
 h2{font-size:17px;color:var(--text-primary);border-bottom:1px solid var(--line);
    padding-bottom:6px;margin-top:36px}
 h3{color:var(--text-primary);margin:20px 0 6px;font-size:14px}
 a{color:var(--accent)}
 table{border-collapse:collapse;width:100%;font-size:13.5px}
 th,td{border-bottom:1px solid var(--line-soft);padding:7px 11px;text-align:left}
 th{color:var(--text-muted);font-size:11px;text-transform:uppercase;letter-spacing:.055em}
 code,pre{background:var(--surface-2);border-radius:5px;padding:1px 5px;font-size:12.5px}
 pre{padding:11px;overflow-x:auto}
 img{max-width:100%;border-radius:8px}
 .grid,.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}
 .card,.item{background:var(--surface-1);border:1px solid var(--line);border-radius:10px;padding:12px}
</style>"""


def strip_local_palette(html: str) -> str:
    """Neutralise the old :root block so the site tokens win."""
    return re.sub(r":root\{--bg:#0f1420;[^}]*\}", "", html, count=1)


def inject(path: Path, active: str, doc_page: bool) -> bool:
    html = path.read_text()
    if MARK in html:
        print(f"  already themed: {path.name}")
        return False
    header = sh.nav(active, 1)
    css = DOC_STYLE if doc_page else ""
    inject_head = ('<meta name="viewport" content="width=device-width,initial-scale=1">'
                   + ('<link rel="stylesheet" href="../assets/app.css">'
                      '<script src="../assets/site.js"></script>' + css
                      if doc_page else APP_TOKENS) + MARK)

    if doc_page:
        html = strip_local_palette(html)

    # head injection: after </title> if present, else at the very top
    if "</title>" in html:
        html = html.replace("</title>", "</title>" + inject_head, 1)
    else:
        html = inject_head + html

    # body injection: right after <body...> if present, else before the first
    # structural element the page uses
    m = re.search(r"<body[^>]*>", html)
    if m:
        html = html[:m.end()] + header + html[m.end():]
    else:
        for anchor in ('<div id=app>', '<nav class=bar>', '<nav class="bar">',
                       '<div class=container>', '<div class="container">', '<h1'):
            if anchor in html:
                html = html.replace(anchor, header + anchor, 1)
                break
        else:
            html = header + html
    path.write_text(html)
    print(f"  themed: {path.name}")
    return True


def fix_inspector_height():
    """The app assumed the full viewport; it now sits under a 52px header."""
    p = MEM / "inspector.html"
    h = p.read_text()
    if "calc(100vh - 52px)" in h:
        return
    h = h.replace("#app{display:flex;height:100vh}",
                  "#app{display:flex;height:calc(100vh - 52px)}")
    p.write_text(h)
    print("  inspector: canvas height adjusted for the header")


def main():
    inject(MEM / "inspector.html", "membranes/inspector.html", doc_page=False)
    fix_inspector_height()
    inject(MEM / "methods.html", "membranes/inspector.html", doc_page=True)
    inject(MEM / "index.html", "membranes/views.html", doc_page=True)


if __name__ == "__main__":
    main()
